name: walletconnect_qrcode_modal_dart
description: Provides UI for DApps to easily connect to a supported Wallet apps through open WalletConnect protocol.
version: 0.0.6
repository: https://github.com/nextchapterstudio/walletconnect_qrcode_modal_dart
issue_tracker: https://github.com/nextchapterstudio/walletconnect_qrcode_modal_dart/issues

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  async: ^2.8.2
  cached_network_image: ^3.2.1
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.3.0
  json_annotation: ^4.5.0
  qr_flutter: ^4.0.0
  url_launcher: ^6.1.4
  walletconnect_dart: ^0.0.11

dev_dependencies:
  build_runner: ^2.1.10
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.2.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter: null
